# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Jue Wang's Academic Homepage"
title_separator          : "-"
name                     : &name "Jue Wang"
description              : &description "PhD Candidate in Mechanical Engineering at Purdue University, specializing in shape-morphing robotics, bio-inspired systems, and machine learning applications."
url                      : "https://yourusername.github.io" # Replace with your GitHub Pages URL, e.g., https://juewang.github.io
baseurl                  : "" # Leave empty if hosting at the root of your GitHub Pages site
repository               : "yourusername/yourusername.github.io" # Replace with your GitHub repository name

# Site Author - The following control what appear as part of the author content on the side bar.
author:
  # Biographic information
  avatar           : "profile.jpg" # Replace with the filename of your profile picture in /images/
  name             : "Jue Wang"
  pronouns         : "" # Add if applicable, e.g., "he/him"
  bio              : "Postdoc Associate in Mechanical Engineering at Yale University, focusing on soft robotics, bio-inspired systems, and machine learning for shape-morphing devices."
  location         : "9 Hillhouse Ave, New Haven, CT, USA" # Based on your affiliation with Purdue University
  employer         : "Yale University"
  uri              : "" # Add your personal website if you have one
  email            : "jue.wang.jw3254@yale.edu" # From your CV

  # Academic websites
  academia         : "" # Add your Academia.edu profile URL if applicable
  arxiv            : "" # Add your arXiv profile URL if applicable
  googlescholar    : "https://scholar.google.com/citations?hl=en&user=JwZ254Ay&cite" # From your CV
  impactstory      : "" # Add if applicable
  orcid            : "" # Add your ORCID URL if you have one
  semantic         : "" # Add your Semantic Scholar URL if applicable
  pubmed           : "" # Add your PubMed URL if applicable
  researchgate     : "" # Add your ResearchGate URL if applicable
  scopus           : "" # Add your Scopus URL if applicable

  # Repositories and software development
  bitbucket        : "" # Add your Bitbucket username if applicable
  codepen          : "" # Add your CodePen username if applicable
  dribbble         : "" # Add your Dribbble username if applicable
  github           : "" # Add your GitHub username, e.g., "juewang"
  kaggle           : "" # Add your Kaggle username if applicable
  stackoverflow    : "" # Add your StackOverflow user ID if applicable

  # Social media
  artstation       : ""
  bluesky          : "" # Add your Bluesky username if applicable
  facebook         : ""
  flickr           : ""
  foursquare       : ""
  goodreads        : ""
  google_plus      : ""
  keybase          : ""
  instagram        : ""
  lastfm           : ""
  linkedin         : "" # Add your LinkedIn username if applicable
  mastodon         : ""
  medium           : ""
  pinterest        : ""
  soundcloud       : ""
  steam            : ""
  telegram         : ""
  tumblr           : ""
  twitter          : "" # Add your Twitter/X username if applicable
  vine             : ""
  weibo            : "" # Add your Weibo username if applicable
  wikipedia        : ""
  xing             : ""
  youtube          : ""
  zhihu            : "" # Add your Zhihu username if applicable

# Publication Category - The following the list of publication categories and their headings
publication_category:
  patents:
    title: 'Patents'
  journal_articles:
    title: 'Journal Articles'
  conference_papers:
    title: 'Conference Papers'
  conference_abstracts:
    title: 'Conference Abstracts'

# Site Settings
teaser                   : "" # Add a teaser image filename in /images/ if desired
breadcrumbs              : true # Enable breadcrumbs for better navigation
words_per_minute         : 160
future                   : true # Show future-dated posts (e.g., upcoming talks)
read_more                : "disabled"
talkmap_link             : false
comments:
  provider               : false # Disable comments unless you want to enable Disqus or another provider
  disqus:
    shortname            : ""
  discourse:
    server               : ""
  facebook:
    appid                : ""
    num_posts            : 5
    colorscheme          : "light"
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "main" # Use "main" instead of "gh-pages" for GitHub Pages
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601"
atom_feed:
  hide                   : false
  path                   : ""

# SEO Related
google_site_verification : ""
bing_site_verification   : ""
alexa_site_verification  : ""
yandex_site_verification : ""

# Social Sharing
twitter:
  username               : *twitter
facebook:
  username               : ""
  app_id                 : ""
  publisher              : ""
og_image                 : "" # Add a default social media image if desired
og_description           : "" # Add a default social media description if desired
social:
  type                   : "Person"
  name                   : "Jue Wang"
  links: # Add links to your social media profiles
    - "https://scholar.google.com/citations?hl=en&user=JwZ254Ay&cite" # Google Scholar
    # Add other links (e.g., LinkedIn, GitHub) if applicable

# Analytics
analytics:
  provider               : "false" # Enable Google Analytics if desired
  google:
    tracking_id          : ""

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# These settings control the types of collections used by the template
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
  projects: # Added for academic projects
    output: true
    permalink: /:collection/:path/

# These settings control how pages and collections are included in the site
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Etc/UTC

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Mimic GitHub Pages with --safe
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development